language: node_js

sudo: required

services:
  - docker

node_js:
  - "12"

arch:
  - amd64

os: 
  - linux

install:
  - npm install

  # Compile OpenCV
  - (cd ./utils && bash ./build.sh)

  # Copy compiled files to root
  - cp ./utils/opencv/build_wasm/bin/opencv.wasm ./opencv.wasm
  - cp ./utils/opencv/build_wasm/bin/opencv.js ./opencv.js

  # Prepare opencv's test
  - cp -r ./utils/opencv/build_wasm/ ./build_wasm_test
  - (cd ./build_wasm_test/bin && npm install)

script:
  # Run opencv's test
  - (cd ./build_wasm_test/bin && node tests.js)
  # Run opencv-wasm's test
  - npm test
