language: node_js

sudo: required

services:
  - docker

node_js:
  - "12"

arch:
  - amd64

os: 
  - linux

install:
  - npm install
  - (cd ./utils && sh ./build.sh)
  - (cd ./utils/opencv/build_wasm/bin && npm install)
  - (cp ./utils/opencv/build_wasm/bin/opencv.wasm ./opencv.wasm)
  - (cp ./utils/opencv/build_wasm/bin/opencv.js ./opencv.js)
  - (cp -r ./utils/opencv/build_wasm/ ./build_wasm_test)
  - (chmod 775 -R ./build_wasm_test)
  - (cd ./build_wasm_test/bin && npm install)

script:
  - (cd ./build_wasm_test/bin && node test.js)
  - npm test
