language: node_js

sudo: required

services:
  - docker

node_js:
  - "12"

arch:
  - amd64

os: 
  - linux

install:
  - npm install

  - cd ./utils
  # - chmod 755 ./build.sh
  - bash ./build.sh
  - cp -a ./opencv/build_wasm/ ./build_wasm
  # - chmod -R 755 ./build_wasm
  - node seperateBinaryFile.js
  - cd ./build_wasm/bin
  - npx js-beautify opencv.js -r
  - cd ../..
  - cd ..

  - cp ./utils/build_wasm/bin/opencv.wasm ./opencv.wasm
  - cp ./utils/build_wasm/bin/opencv.js ./opencv.js
  - cp -r ./utils/opencv/build_wasm/ ./build_wasm_test

  - cd ./build_wasm_test/bin
  - npm install
  - cd ../..

script:
  - cd ./build_wasm_test/bin
  - node test.js
  - cd ..

  - npm test
